#!/bin/sh
set -eux

source configs/default

if [ -z ${GITHUB_ACTIONS+x} ]; then
  # we are not on GA
  if [ $(nproc) -gt 2 ]; then
    numproc=$(($(nproc) - 2))
  else
    numproc=1
  fi
else
  # we are on GA
  numproc=2
fi

RELEASE_METAS=$(gh release view "${TOOLS_TAG}" --json assets --jq '.assets')
METAS=""
for name in llvm.zip aarch64-gcc.zip x86_64-gcc.zip; do
  API_URL=$(echo "${RELEASE_METAS}" | jq -r ".[] | select(.name == \"${name}\") | .apiUrl")
  if [ -z "${API_URL}" ]; then
    echo "Cannot find asset ${name} in release ${TOOLS_TAG}"
    exit 1
  fi
  META=$(gh api "${API_URL}" --jq '{name, digest: (.digest | sub("^sha256:"; "")), url: .browser_download_url}')
  METAS=$(printf '%s\n%s' "${METAS}" "${META}")
done

METAS=$(jq -s '.' <(printf "${METAS}"))

cd superconfigure/cosmopolitan

python3 - >tool/cosmocc/package.sh.tmp <<EOF
import re

files = ${METAS}
import re
with open('tool/cosmocc/package.sh', 'r') as f:
  content = f.read()
for f in files:
  pattern = re.compile(r'fetch.*?{}.*?&'.format(f['name']))
  replacement = f'fetch {f["url"]} {f["digest"]} &'
  content = pattern.sub(replacement, content)
print(content)
EOF

cat tool/cosmocc/package.sh.tmp

mkdir cosmocc -p
bash tool/cosmocc/package.sh.tmp cosmocc
