#!/bin/sh
set -eux

if [ -z ${GITHUB_ACTIONS+x} ]; then
  # we are not on GA
  if [ $(nproc) -gt 2 ]; then
    numproc=$(($(nproc) - 2))
  else
    numproc=1
  fi
else
  # we are on GA
  numproc=2
fi

cd superconfigure/cosmopolitan

python3 - >tool/cosmocc/package.sh.tmp <<EOF
import re
hashes = {
  'aarch64-gcc.zip': '580076b885b469a0e819dc6ee37aa2dfae3ec1db7d864c406ad813fc4297996c',
  'x86_64-gcc.zip': 'cdc54e48a521aabd8488ebfc66aba000f556ed70c6918f194a825e770e8bf3eb',
  'llvm.zip': '7dfa4007c9caf65e3f4871beddd5c730f0e1deb13a43050318c6dfdf20fa44ce',
}
import re
with open('tool/cosmocc/package.sh', 'r') as f:
  content = f.read()
for filename, sha256 in hashes.items():
  pattern = re.compile(r'fetch.*?{}.*?&'.format(filename))
  replacement = f'fetch https://github.com/hsfzxjy/cosmocc-repack/releases/download/4.0.2-28-ge7e5856b8/{filename} {sha256} &'
  content = pattern.sub(replacement, content)
print(content)
EOF

cat tool/cosmocc/package.sh.tmp

mkdir cosmocc -p
bash tool/cosmocc/package.sh.tmp cosmocc
