#!/bin/sh
set -eux

echo "Initial Setup"
export BASELOC="$PWD/superconfigure"
export COSMO="$BASELOC"/cosmopolitan
export RESULTS="$BASELOC"/results

# zip them up
echo "zip file with actually portable executables"
cd "$RESULTS"

# rename to remove .com extension
for COMFILE in $(find . -name "*.com"); do
    NEWFILE="${COMFILE%.*}"
    mv "$COMFILE" "$NEWFILE"
done

for FILE in $(find .); do
    touch -d "1970-01-01 00:00+0000" -a -m "$FILE"
done

ZFILE="$BASELOC/${ZFILENAME:-extras}.zip"
zip -X --symlinks "$ZFILE" $(find . -name "*" | grep -v "\.x86" | grep -v "\.aarch64")

ZFILE="$BASELOC/${ZFILENAME:-extras}-dbg.zip"
zip -X --symlinks "$ZFILE" $(find . -name "*" -type f)
