#!/usr/bin/env bash
set -x

source "$(dirname `realpath $0`)/../../configs/default"

git clone https://github.com/ahgamut/superconfigure.git
cd superconfigure
git checkout "$SC_REF"

# cosmo
git clone https://github.com/hsfzxjy/cosmopolitan.git
cd cosmopolitan
git remote add upstream https://github.com/jart/cosmopolitan.git
git fetch upstream --tags

git checkout "$COSMO_REF"
