#!/usr/bin/env bash
set -x

# update?
sudo apt update

# ssl certs
sudo apt-get install -y ca-certificates libssl-dev \
    qemu-user qemu-system-x86 qemu-system-arm qemu-utils qemu-user-static \
    texinfo groff libtool \
    cmake ninja-build bison zip \
    pkg-config build-essential autoconf re2c

# the zip folder
sudo mkdir -p /zip
sudo chmod -R 0777 /zip

cd superconfigure/cosmopolitan

sudo cp build/bootstrap/ape.elf /usr/bin/ape
sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"
sudo sh -c "echo ':APE-jart:M::jartsr::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"
sudo sh -c "echo ':qemu-aarch64:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-aarch64:CF' >/proc/sys/fs/binfmt_misc/register"

ls /proc/sys/fs/binfmt_misc/
